// Copyright © 2008-2009 Vidar Wahlberg <canidae@exent.net>
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
package net.exent.locutus.gui;

/**
 *
 * @author canidae
 */
public class Help extends javax.swing.JPanel {

    /** Creates new form Help */
    public Help() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                keyboardScrollPane = new javax.swing.JScrollPane();
                keyboardPanel = new javax.swing.JPanel();
                keyLabel = new javax.swing.JLabel();
                descriptionLabel = new javax.swing.JLabel();
                horizontalSeparator = new javax.swing.JSeparator();
                verticalSeparator = new javax.swing.JSeparator();
                aKeyLabel = new javax.swing.JLabel();
                aDescriptionLabel = new javax.swing.JLabel();
                aShiftKeyLabel = new javax.swing.JLabel();
                aShiftDescriptionLabel = new javax.swing.JLabel();
                tKeyLabel = new javax.swing.JLabel();
                tDescriptionLabel = new javax.swing.JLabel();
                tShiftKeyLabel = new javax.swing.JLabel();
                tShiftDescriptionLabel = new javax.swing.JLabel();
                fKeyLabel = new javax.swing.JLabel();
                fDescriptionLabel = new javax.swing.JLabel();
                fShiftKeyLabel = new javax.swing.JLabel();
                fShiftDescriptionLabel = new javax.swing.JLabel();
                dKeyLabel = new javax.swing.JLabel();
                dDescriptionLabel = new javax.swing.JLabel();
                sKeyLabel = new javax.swing.JLabel();
                sDescriptionLabel = new javax.swing.JLabel();
                eKeyLabel = new javax.swing.JLabel();
                eDescriptionLabel = new javax.swing.JLabel();
                rKeyLabel = new javax.swing.JLabel();
                rDescriptionLabel = new javax.swing.JLabel();
                spaceKeyLabel = new javax.swing.JLabel();
                spaceDescriptionLabel = new javax.swing.JLabel();
                spaceCtrlKeyLabel = new javax.swing.JLabel();
                spaceCtrlDescriptionLabel = new javax.swing.JLabel();
                gKeyLabel = new javax.swing.JLabel();
                gDescriptionLabel = new javax.swing.JLabel();
                gShiftKeyLabel = new javax.swing.JLabel();
                gShiftDescriptionLabel = new javax.swing.JLabel();

                setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

                keyboardPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Keyboard shortcuts"));
                keyboardPanel.setLayout(new java.awt.GridBagLayout());

                keyLabel.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13)); // NOI18N
                keyLabel.setText("Key");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(keyLabel, gridBagConstraints);

                descriptionLabel.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13));
                descriptionLabel.setText("Description");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(descriptionLabel, gridBagConstraints);
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.gridwidth = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                keyboardPanel.add(horizontalSeparator, gridBagConstraints);

                verticalSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.gridheight = 16;
                gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                keyboardPanel.add(verticalSeparator, gridBagConstraints);

                aKeyLabel.setText("A");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(aKeyLabel, gridBagConstraints);

                aDescriptionLabel.setText("Next album");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(aDescriptionLabel, gridBagConstraints);

                aShiftKeyLabel.setText("Shift-A");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(aShiftKeyLabel, gridBagConstraints);

                aShiftDescriptionLabel.setText("Previous album");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(aShiftDescriptionLabel, gridBagConstraints);

                tKeyLabel.setText("T");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 4;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(tKeyLabel, gridBagConstraints);

                tDescriptionLabel.setText("Next track");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 4;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(tDescriptionLabel, gridBagConstraints);

                tShiftKeyLabel.setText("Shift-T");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 5;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(tShiftKeyLabel, gridBagConstraints);

                tShiftDescriptionLabel.setText("Previous track");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 5;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(tShiftDescriptionLabel, gridBagConstraints);

                fKeyLabel.setText("F");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 8;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(fKeyLabel, gridBagConstraints);

                fDescriptionLabel.setText("Next file");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 8;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(fDescriptionLabel, gridBagConstraints);

                fShiftKeyLabel.setText("Shift-F");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 9;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(fShiftKeyLabel, gridBagConstraints);

                fShiftDescriptionLabel.setText("Previous file");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 9;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(fShiftDescriptionLabel, gridBagConstraints);

                dKeyLabel.setText("D/Delete");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 11;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(dKeyLabel, gridBagConstraints);

                dDescriptionLabel.setText("Mark all selected files or files in selected albums/tracks as wrongly identified. This is only necessary when a file was supposed to match another track");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 11;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(dDescriptionLabel, gridBagConstraints);

                sKeyLabel.setText("S/Enter");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 10;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(sKeyLabel, gridBagConstraints);

                sDescriptionLabel.setText("Mark all selected files or files in selected albums/tracks as correctly identified");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 10;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(sDescriptionLabel, gridBagConstraints);

                eKeyLabel.setText("E");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 13;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(eKeyLabel, gridBagConstraints);

                eDescriptionLabel.setText("Expand all nodes in current album/group");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 13;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(eDescriptionLabel, gridBagConstraints);

                rKeyLabel.setText("R/Escape");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 12;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(rKeyLabel, gridBagConstraints);

                rDescriptionLabel.setText("Unmark all selected files or files in selected albums/tracks");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 12;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(rDescriptionLabel, gridBagConstraints);

                spaceKeyLabel.setText("Space");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 14;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(spaceKeyLabel, gridBagConstraints);

                spaceDescriptionLabel.setText("Commit changes for marked files in active album/group");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 14;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(spaceDescriptionLabel, gridBagConstraints);

                spaceCtrlKeyLabel.setText("Ctrl-Space");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 15;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(spaceCtrlKeyLabel, gridBagConstraints);

                spaceCtrlDescriptionLabel.setText("Commit changes for all marked files in every album/group");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 15;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.weightx = 1.0;
                gridBagConstraints.weighty = 1.0;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(spaceCtrlDescriptionLabel, gridBagConstraints);

                gKeyLabel.setText("G");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 6;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(gKeyLabel, gridBagConstraints);

                gDescriptionLabel.setText("Next group");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 6;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(gDescriptionLabel, gridBagConstraints);

                gShiftKeyLabel.setText("Shift-G");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 7;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(gShiftKeyLabel, gridBagConstraints);

                gShiftDescriptionLabel.setText("Previous group");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 7;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
                keyboardPanel.add(gShiftDescriptionLabel, gridBagConstraints);

                keyboardScrollPane.setViewportView(keyboardPanel);

                add(keyboardScrollPane);
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel aDescriptionLabel;
        private javax.swing.JLabel aKeyLabel;
        private javax.swing.JLabel aShiftDescriptionLabel;
        private javax.swing.JLabel aShiftKeyLabel;
        private javax.swing.JLabel dDescriptionLabel;
        private javax.swing.JLabel dKeyLabel;
        private javax.swing.JLabel descriptionLabel;
        private javax.swing.JLabel eDescriptionLabel;
        private javax.swing.JLabel eKeyLabel;
        private javax.swing.JLabel fDescriptionLabel;
        private javax.swing.JLabel fKeyLabel;
        private javax.swing.JLabel fShiftDescriptionLabel;
        private javax.swing.JLabel fShiftKeyLabel;
        private javax.swing.JLabel gDescriptionLabel;
        private javax.swing.JLabel gKeyLabel;
        private javax.swing.JLabel gShiftDescriptionLabel;
        private javax.swing.JLabel gShiftKeyLabel;
        private javax.swing.JSeparator horizontalSeparator;
        private javax.swing.JLabel keyLabel;
        private javax.swing.JPanel keyboardPanel;
        private javax.swing.JScrollPane keyboardScrollPane;
        private javax.swing.JLabel rDescriptionLabel;
        private javax.swing.JLabel rKeyLabel;
        private javax.swing.JLabel sDescriptionLabel;
        private javax.swing.JLabel sKeyLabel;
        private javax.swing.JLabel spaceCtrlDescriptionLabel;
        private javax.swing.JLabel spaceCtrlKeyLabel;
        private javax.swing.JLabel spaceDescriptionLabel;
        private javax.swing.JLabel spaceKeyLabel;
        private javax.swing.JLabel tDescriptionLabel;
        private javax.swing.JLabel tKeyLabel;
        private javax.swing.JLabel tShiftDescriptionLabel;
        private javax.swing.JLabel tShiftKeyLabel;
        private javax.swing.JSeparator verticalSeparator;
        // End of variables declaration//GEN-END:variables

}
