/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Locutus.java
 *
 * Created on Aug 27, 2009, 10:35:02 PM
 */
package net.exent.locutus.gui;

import java.sql.SQLException;
import net.exent.locutus.database.Database;

/**
 *
 * @author canidae
 */
public class Locutus extends javax.swing.JFrame {

	/** Creates new form Locutus */
	public Locutus() {
		try {
			Database.connectPostgreSQL("jdbc:postgresql://exent.net/locutus", "locutus", "locutus");
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTabbedPane1 = new javax.swing.JTabbedPane();
                matching1 = new net.exent.locutus.gui.Matching();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jTabbedPane1.addTab("Matching", matching1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new Locutus().setVisible(true);
			}
		});
	}
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTabbedPane jTabbedPane1;
        private net.exent.locutus.gui.Matching matching1;
        // End of variables declaration//GEN-END:variables
}
