/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Settings.java
 *
 * Created on Oct 10, 2009, 9:17:05 PM
 */

package net.exent.locutus.gui;

/**
 *
 * @author canidae
 */
public class Settings extends javax.swing.JPanel {

    /** Creates new form Settings */
    public Settings() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                settingsScrollPane = new javax.swing.JScrollPane();
                settingsTable = new javax.swing.JTable();

                setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

                settingsTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null},
                                {null, null},
                                {null, null},
                                {null, null}
                        },
                        new String [] {
                                "Key", "Value"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class, java.lang.Object.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }
                });
                settingsScrollPane.setViewportView(settingsTable);

                add(settingsScrollPane);
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane settingsScrollPane;
        private javax.swing.JTable settingsTable;
        // End of variables declaration//GEN-END:variables

}
