/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Settings.java
 *
 * Created on Oct 10, 2009, 9:17:05 PM
 */
package net.exent.locutus.gui;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import net.exent.locutus.database.Database;

/**
 *
 * @author canidae
 */
public class Settings extends javax.swing.JPanel {

	/** Creates new form Settings */
	public Settings() {
		initComponents();
	}

	public void updateTable() {
		DefaultTableModel table = (DefaultTableModel) settingsTable.getModel();
		table.setRowCount(0);
		try {
			ResultSet rs = Database.getSettingList(Locutus.getFilter());
			if (rs == null)
				return;

			while (rs.next()) {
				table.addRow(new Object[]{rs.getString("key"), rs.getString("value")});
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                settingsScrollPane = new javax.swing.JScrollPane();
                settingsTable = new javax.swing.JTable();

                addComponentListener(new java.awt.event.ComponentAdapter() {
                        public void componentHidden(java.awt.event.ComponentEvent evt) {
                                formComponentHidden(evt);
                        }
                        public void componentShown(java.awt.event.ComponentEvent evt) {
                                formComponentShown(evt);
                        }
                });
                setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

                settingsTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Key", "Value"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class, java.lang.Object.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }
                });
                settingsScrollPane.setViewportView(settingsTable);

                add(settingsScrollPane);
        }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
	    Locutus.hideMetadata();
	    updateTable();
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
	    Locutus.showMetadata();
    }//GEN-LAST:event_formComponentHidden
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane settingsScrollPane;
        private javax.swing.JTable settingsTable;
        // End of variables declaration//GEN-END:variables
}
