/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Detached.java
 *
 * Created on Sep 4, 2009, 9:43:30 PM
 */
package net.exent.locutus.gui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import net.exent.locutus.data.Metafile;
import net.exent.locutus.database.Database;

/**
 *
 * @author canidae
 */
public class Uncompared extends javax.swing.JPanel {

	/** Creates new form Detached */
	public Uncompared() {
		initComponents();
	}

	public void updateTree() {
		DefaultTreeModel model = (DefaultTreeModel) uncomparedTree.getModel();
		DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
		List<DefaultMutableTreeNode> remove = new ArrayList<DefaultMutableTreeNode>();
		Enumeration groups = root.children();
		while (groups.hasMoreElements())
			remove.add((DefaultMutableTreeNode) groups.nextElement());
		for (DefaultMutableTreeNode r : remove)
			model.removeNodeFromParent(r);

		try {
			ResultSet rs = Database.getUncompared(Locutus.getFilter());
			if (rs == null)
				return;

			DefaultMutableTreeNode group = null;
			while (rs.next()) {
				Metafile mf = new Metafile();
				mf.setUncomparedData(rs);
				if (group == null || !mf.getGroup().equals(group.getUserObject())) {
					if (group != null)
						model.insertNodeInto(group, root, model.getChildCount(root));
					group = new DefaultMutableTreeNode(mf.getGroup());
				}
				model.insertNodeInto(new DefaultMutableTreeNode(mf), group, model.getChildCount(group));
			}
			if (group != null)
				model.insertNodeInto(group, root, model.getChildCount(root));
		} catch (SQLException e) {
			e.printStackTrace();
		}
		model.setRoot(root);
		uncomparedTree.requestFocus();
		if (uncomparedTree.getRowCount() > 0)
			uncomparedTree.setSelectionRow(0);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                uncomparedTree = new javax.swing.JTree();

                addComponentListener(new java.awt.event.ComponentAdapter() {
                        public void componentShown(java.awt.event.ComponentEvent evt) {
                                formComponentShown(evt);
                        }
                });

                javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
                uncomparedTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
                uncomparedTree.setRootVisible(false);
                jScrollPane1.setViewportView(uncomparedTree);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                );
        }// </editor-fold>//GEN-END:initComponents

	private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
		updateTree();
	}//GEN-LAST:event_formComponentShown
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTree uncomparedTree;
        // End of variables declaration//GEN-END:variables
}
